py3 compatibility: fix the reference before assignment
The fix solves Python 3 error when variable 'ex' is used on line 69:

'''
UnboundLocalError: local variable 'ex' referenced before assignment
'''

Signed-off-by: Jan Beran <jberan@redhat.com>