py3: Exception does not have message member
```
try:
    raise Exception("ABC")
except Exception as e:
    print(e)
    print(e.message)
```

In python2 the above code prints:
```
ABC
ABC
```
but in python3 it prints:
```
ABC   <---------------- print(e)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
Exception: ABC

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
AttributeError: 'Exception' object has no attribute 'message'
```

Signed-off-by: Matej Marusak <mmarusak@redhat.com>