Revert "pyfaf: use the common add_repo argument in reposync action"
This reverts commit 273ce362d94d5d9fb36cb54ada18b540cdb8c607.

Breaks reposync:
Traceback (most recent call last):
  File "/bin/faf", line 140, in <module>
    main()
  File "/bin/faf", line 119, in main
    exitcode = cmdline.func(cmdline, db)
  File "/usr/lib/python2.7/site-packages/pyfaf/actions/reposync.py", line 40, in run
    if cmdline.NAME and repo.name not in cmdline.NAME:
AttributeError: 'Namespace' object has no attribute 'NAME'

Needs better patch.