config: Use https to connect to kojihub
Action mark-probably-fixed action failed with error:
CRITICAL:
  faf: Action failed unexpectedly:
    HTTPError: 405 Client Error: Method Not Allowed

Signed-off-by: Martin Kutlak <mkutlak@redhat.com>
(cherry picked from commit 39a64e5673cb840c4c6630d1d6a51bab1fdab903)