tests: Add test_webfaf path due to unit2-3
The fix solves the following issue: if 'unit-3' runs
from 'tests' directory, it fails on webfaf tests:
'''
ImportError: cannot import name 'WebfafTestCase'
'''

Signed-off-by: Jan Beran <jberan@redhat.com>