py3 compatibility: avoid dictionary change in the cycle
The original code fails in Python 3 due to the pop function
because there is used an iterator to func_thread_map in the cycle
while Python 2 makes a copy:

'''
RuntimeError: dictionary changed size during iteration
'''

The forced copy of func_thread_map solves the problem.

Signed-off-by: Jan Beran <jberan@redhat.com>